djangoProject_phonebook/urls.py
from django.urls import include, path
from django.contrib import admin
urlpatterns = [
    path(r'phonebook/', include('phonebook.urls')),
    path(r'admin/', admin.site.urls),
]

phonebook/urls.py
from django.urls import path, re_path

from phonebook import views
# новые import для API
from django.conf.urls import include
from phonebook.api import PhonebookResource, OptionResource
from tastypie.api import Api
# api_name будет указываться в URLах
# перед resource_name из api.py
api = Api(api_name='api')
api.register(PhonebookResource())
api.register(OptionResource())

app_name = 'phonebook'
urlpatterns = [
    path(r'', views.index, name='index'),
    re_path(r'^([0-9]+)/$', views.detail, name='detail'),
    # re_path(r'^([0-9]+)/answer/$', views.answer, name='answer'),
    re_path(r'^([0-9]+)/post/$', views.post, name='post'),

# отправка списка сообщений
    re_path(r'^([0-9]+)/msg_list/$', views.msg_list, name='msg_list'),
#  # отправка оценки
    re_path(r'^([0-9]+)/post_mark/$', views.post_mark, name='post_mark'),
# # средняя оценка
    re_path(r'^([0-9]+)/get_mark/$',views.get_mark, name='get_mark'),
    re_path(r'^admin/$', views.admin, name='admin'),
    #new person
    re_path(r'^post_client/$', views.post_riddle, name='post_client'),
    re_path(r'^subscribe/$', views.SubscribeView.as_view()),
    re_path(r'^unsubscribe/$', views.unsubscribe, name='unsubscribe'),
# для API
    re_path(r'^', include(api.urls)),
    re_path(r'^register/$', views.RegisterFormView.as_view()),
    re_path(r'^login/$', views.LoginFormView.as_view()),
    re_path(r'^logout/$', views.LogoutView.as_view()),
    re_path(r'^password-change/', views.PasswordChangeView.as_view()),


]

phonebook/models.py
from django.db import models
# встроенная модель пользователя
# нужна для авторов сообщений
from django.contrib.auth.models import User
# тип "временнАя зона" для получения текущего времени
from django.utils import timezone

# Create your models here.
class Name(models.Model):
    person_name = models.CharField(max_length=255)
    pub_date = models.DateTimeField('date published')

class Detail(models.Model):
    name = models.ForeignKey(Name, on_delete=models.CASCADE)
    phone = models.CharField(max_length=255)
    email = models.CharField(max_length=255)

class Message(models.Model):
    chat = models.ForeignKey(
        Name,
        verbose_name='Чат под именем',
        on_delete=models.CASCADE)
    author = models.ForeignKey(
        User,
        verbose_name='Пользователь', on_delete=models.CASCADE)
    message = models.TextField('Сообщение')
    pub_date = models.DateTimeField(
        'Дата сообщения',
        default=timezone.now)

class Mark(models.Model):
    name = models.ForeignKey(
        Name,
        verbose_name='Загадка',
        on_delete=models.CASCADE)
    author = models.ForeignKey(
        User,
        verbose_name='Пользователь', on_delete=models.CASCADE)
    mark = models.IntegerField(
        verbose_name='Оценка')
    pub_date = models.DateTimeField(
        'Дата оценки',
        default=timezone.now)

templates/admin.html
{% extends 'base.html' %}
{% block main %}
    {% if user.is_staff %}
        <div class="card mb-3">
            <div class="card-body">
                <form action="../post_client/" method="post">
                    {% csrf_token %}
                    <h5>Add person:</h5>
                    <div class="mb-3">
                        <input class="form-control"
                               placeholder="Person name"
                               name="text"
                               required/>
                    </div>
                    <div class="card mb-3">
                        <div class="card-body" id="orders_new">
                            <h6>Add details:</h6>
                            <div class="mb-3">
                                <input class="form-control"
                                       placeholder="phone number"
                                       name="description"
                                       required/>
                            </div>
                            <div class="mb-3">
                                <input class="form-control"
                                       placeholder="email"
                                       name="qty"
                                       required/>
                            </div>
                        </div>
                    </div>
                    <div class="mb-3">
                        <button class="btn btn-success" type="submit">
                            Save
                        </button>
                    </div>

                </form>
            </div>
        </div>
{#        <h4 class="card-title">Available People</h4>#}

{% if message %}
<p class="alert alert-success">
<strong>{{ message }}</strong>
</p>
{% endif %}
{% if latest_names %}
<ul>
{% for name in latest_names %}
 <li>
                <a href="/phonebook/{{ name.id }}/">
                    {{ name.person_name }}
                </a>
            </li>
{% endfor %}
</ul>
{% else %}
{#<p>No people are available right now.</p>#}
{% endif %}
    {% else %}
        <h4>Access denied.</h4>
    {% endif %}
{% endblock %}

templates/answer.html
{% extends 'base.html' %}
{% block main %}
<h2>{{ name.person_name}}</h2>

<ul> {% for order in orders %}
        <li> Description: {{ order.description }} </li>
        <li> Qty: {{ order.qty }} </li>
        <li> Date: {{ order.date }} </li>
    <br>
    {% endfor %}
    </ul>
    <hr>
    <hr>
<hr>
<h4>Rating</h4>
<p>Average rating:
<span id="avg_mark_span">
{{ avg_mark }}
</span>
</p>
{% if user.is_authenticated %}
{% if already_rated_by_user <= 0 or already_rated_by_user == None %}
<form action="post_mark/" method="post">
{% csrf_token %}
<div class="row">
<div class="col-sm text-center">
<input name="mark"
type="radio"
value="1"/> 1
</div>
<div class="col-sm text-center">
<input name="mark"
type="radio"
value="2"/> 2

</div>
<div class="col-sm text-center">
<input name="mark"
type="radio"
value="3"/> 3

</div>

<div class="col-sm text-center">

<input name="mark"
type="radio"
value="4"/> 4

</div>

<div class="col-sm text-center">

<input name="mark"
type="radio"
value="5"/> 5
</div>
<div class="col-sm text-center">
<input class="btn btn-success"
type="submit"
value="Send mark"/>

</div>
</div>
</form>
{% else %}
Your rating: {{ user_rating }}
{% endif %}


{% endif %}
<hr>
<h4>Chat</h4>
{% if user.is_authenticated %}
    <form action="post/" method="post">
    {% csrf_token %}
    <div class="input-group mb-3">
      <input type="text"
             class="form-control"
             placeholder="Your message"
             name="message"/>
      <div class="input-group-append">
        <input class="btn btn-success"
                type="submit"
                value="Send"/>
      </div>
    </div>
</form>
{% endif %}
    <div id="history">
    {% for message in latest_messages %}
        <div class="card">
        <div class="card-body">
            <strong>
                {{ message.author.username }}
            </strong>
            <br/>
            <em>
                {{ message.pub_date|date:'Y-m-d H:i:s' }}
            </em>
            <br/>
            {{ message.message }}
        </div>
        </div>
        <br/>
    {% endfor %}
</div>
<script src="https://code.jquery.com/jquery-3.4.1.min.js">
</script>
<script>
function send_msg_update_request(){
    $.get("msg_list/",{},parse_msg_update_response);
    $.get("get_mark/",{},parse_mark_update_response);
}


function parse_msg_update_response(data, success){
    //alert(data);
    res = JSON.parse(data);
    res_str = "";
    for(i=0;i<res.length;i++){
        // HTML-код вставляемых блоков с сообщениями
        // скопирован выше - тот, что выводится
        // при загрузке страницы
        res_str += '<div class="card">\n' +
            '        <div class="card-body">\n' +
            '            <strong>\n' +
            '                '+res[i].author__username+'\n' +
            '            </strong>\n' +
            '            <br/>\n' +
            '            <em>\n' +
            '                '+res[i].pub_date+'\n' +
            '            </em>\n' +
            '            <br/>\n' +
            '            '+res[i].message+'\n' +
            '        </div>\n' +
            '        </div>\n' +
            '        <br/>'
    }
    $("#history").html(res_str);
}
function parse_mark_update_response(data, success){
    res = JSON.parse(data);
    $("#avg_mark_span").html(res["mark__avg"].toFixed(1));
}
setInterval(send_msg_update_request, 5000);
</script>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head> <meta charset="utf-8">


<p class="text-right">
Hello, {{ user.username }}!
<a href="/phonebook/logout">Log out</a> |
<a href="/phonebook/password-change">Change password</a>
{% if user.is_staff %}
| <a href="/phonebook/admin">Admin panel</a>
{% endif %}
{% if user.email == '' %}
| <a href="/phonebook/subscribe">Subscribe</a>
{% else %}
| <a href="/phonebook/unsubscribe">Unsubscribe</a>
{% endif %}
</p>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <title>Phonebook</title> </head> <body> <div class="container"> <div class="row justify-content-center">
    <div class="col-8">
        <h1 class="mt-2">Phonebook</h1> {% if user.is_authenticated %} <p class="text-right"> Hello, {{ user.username }}! <a href="/phonebook/logout">Log out</a> | <a href="/phonebook/password-change"> Change password </a>
    </p> {% else %} <p class="text-right"> <a href="/phonebook/login">Log in</a> | <a href="/phonebook/register">Register</a>
    </p> {% endif %} <hr class="mt-0 mb-4"> <div class="card"> <div class="card-body">
        {% block main %} {% endblock %} </div>
    </div> </div> </div> </div> </body> </html>


{#<!doctype html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="utf-8">#}
{#    <meta name="viewport"#}
{#          content="width=device-width, initial-scale=1, shrink-to-fit=no">#}
{#    <link rel="stylesheet"#}
{#          href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">#}
{#    <title>Orders</title>#}
{#</head>#}
{#<body>#}
{#<div class="container">#}
{#    <div class="row justify-content-center">#}
{#        <div class="col-8">#}
{#            <h1 class="mt-2">Clients and orders</h1>#}
{#            {% if user.is_authenticated %}#}
{#                <p class="text-right">#}
{#                    Hello, {{ user.username }}!#}
{#                    <a href="/phonebook/logout">Log out</a> |#}
{#                    <a href="/phonebook/password-change">#}
{#                        Change password#}
{#                    </a>#}
{#                    {% if user.is_staff %}#}
{#                        | <a href="/phonebook/admin">Admin panel</a>#}
{#                    {% endif %}#}
{#                    {% if user.email == '' %}#}
{#                        | <a href="/phonebook/subscribe">Subscribe</a>#}
{#                    {% else %}#}
{#                        | <a href="/phonebook/unsubscribe">Unsubscribe</a>#}
{#                    {% endif %}#}
{#                </p>#}
{#            {% else %}#}
{#                <p class="text-right">#}
{#                    <a href="/phonebook/login">Log in</a> |#}
{#                    <a href="/phonebook/register">Register</a>#}
{#                </p>#}
{#            {% endif %}#}
{##}
{#            <hr class="mt-0 mb-4">#}
{#            <div class="card">#}
{#                <div class="card-body">#}
{#                    {% block main %}#}
{#                    {% endblock %}#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}
{#</body>#}
{#</html>#}

templates/details.html
{% extends 'base.html' %}
{% block main %}
<h1>{{ name.person_name }}</h1>
<p><strong>{{ method }}</strong></p>
{% if error_message %}
    <p>
        <strong>{{ error_message }}</strong>
    </p>
{% endif %}
{% csrf_token %}
{% for detail in name.detail_set.all %}
    <label for="detail{{ forloop.counter }}">
        <p2>Phone:{{ detail.phone }}</p2> <br>
         <p2>Email:{{ detail.email }}</p2>
    <hr>
    </label><br>
    {% endfor %}
<h4>Rating</h4>
    <p>Average rating:
        <span id="avg_mark_span">
            {{ avg_mark }}
        </span>
    </p>
{% if user.is_authenticated %}
    {% if already_rated_by_user <= 0 or already_rated_by_user ==  None %}
        <form action="post_mark/" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-sm text-center">
                    <input name="mark"
                           type="radio"
                           value="1"/> 1
                </div>
                <div class="col-sm text-center">
                    <input name="mark"
                           type="radio"
                           value="2"/> 2
                </div>
                <div class="col-sm text-center">
                    <input name="mark"
                           type="radio"
                           value="3"/> 3
                </div>
                <div class="col-sm text-center">
                    <input name="mark"
                           type="radio"
                           value="4"/> 4
                </div>
                <div class="col-sm text-center">
                    <input name="mark"
                           type="radio"
                           value="5"/> 5
                </div>
                <div class="col-sm text-center">
                    <input class="btn btn-success"
                        type="submit"
                        value="Send mark"/>
                </div>
            </div>
        </form>
        {% else %}
        Your rating: {{ user_rating }}
    {% endif %}

{% endif %}
<hr>
<h4>Chat</h4>
{% if user.is_authenticated %}
    <form action="post/" method="post">
    {% csrf_token %}
    <div class="input-group mb-3">
      <input type="text"
             class="form-control"
             placeholder="Your message"
             name="message"/>
      <div class="input-group-append">
        <input class="btn btn-success"
                type="submit"
                value="Send"/>
      </div>
    </div>
</form>
{% endif %}
    <div id="history">
    {% for message in latest_messages %}
        <div class="card">
        <div class="card-body">
            <strong>
                {{ message.author.username }}
            </strong>
            <br/>
            <em>
                {{ message.pub_date|date:'Y-m-d H:i:s' }}
            </em>
            <br/>
            {{ message.message }}
        </div>
        </div>
        <br/>
    {% endfor %}
</div>
<script src="https://code.jquery.com/jquery-3.4.1.min.js">
</script>




<script>


function send_msg_update_request(){
    $.get("msg_list/",{},parse_msg_update_response);
}


function parse_msg_update_response(data, success){
    //alert(data);
    res = JSON.parse(data);
    res_str = "";
    for(i=0;i<res.length;i++){
        // HTML-код вставляемых блоков с сообщениями
        // скопирован выше - тот, что выводится
        // при загрузке страницы
        res_str += '<div class="card">\n' +
            '        <div class="card-body">\n' +
            '            <strong>\n' +
            '                '+res[i].author__username+'\n' +
            '            </strong>\n' +
            '            <br/>\n' +
            '            <em>\n' +
            '                '+res[i].pub_date+'\n' +
            '            </em>\n' +
            '            <br/>\n' +
            '            '+res[i].message+'\n' +
            '        </div>\n' +
            '        </div>\n' +
            '        <br/>'
    }
    $("#history").html(res_str);
}
function parse_mark_update_response(data, success){
    res = JSON.parse(data);
    $("#avg_mark_span").html(res["mark__avg"].toFixed(1));
}
setInterval(send_msg_update_request, 5000);
</script>
{% endblock %}



{#{% extends 'base.html' %}#}
{#{% block main %}#}
{#<h4 class="card-title">{{ riddle.detail_text }}</h4>#}
{#{% if error_message %}#}
{#<p class="alert alert-danger">#}
{#<strong>{{ error_message }}</strong>#}
{#</p>#}
{#{% endif %}#}
{#{% endblock %}#}

{#{% extends 'base.html' %}#}
{#{% block main %}#}
{#    {% if user.is_staff %}#}
{#        <div class="card mb-3">#}
{#            <div class="card-body">#}
{#                <form action="../post_client/" method="post">#}
{#                    {% csrf_token %}#}
{#                    <h5>Add client:</h5>#}
{#                    <div class="mb-3">#}
{#                        <input class="form-control"#}
{#                               placeholder="Client name"#}
{#                               name="text"#}
{#                               required/>#}
{#                    </div>#}
{#                    <div class="card mb-3">#}
{#                        <div class="card-body" id="orders_new">#}
{#                            <h6>Add orders:</h6>#}
{#                            <div class="mb-3">#}
{#                                <input class="form-control"#}
{#                                       placeholder="description"#}
{#                                       name="description"#}
{#                                       required/>#}
{#                            </div>#}
{#                            <div class="mb-3">#}
{#                                <input class="form-control"#}
{#                                       placeholder="qty"#}
{#                                       name="qty"#}
{#                                       required/>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
{#                    <div class="mb-3">#}
{#                        <button class="btn btn-success" type="submit">#}
{#                            Save#}
{#                        </button>#}
{#                    </div>#}
{##}
{#                </form>#}
{#            </div>#}
{#        </div>#}
{#        <div class="card mb-3">#}
{#            <div class="card-body">#}
{#                <h4 class="card-title">List of clients</h4>#}
{#                {% if clients %}#}
{#                    <ul> {% for client in clients %}#}
{#                        <li><a href="/orders/{{ client.id }}/"> {{ client.client_name }} </a></li>#}
{#                    {% endfor %}#}
{#                    </ul>#}
{#                {% else %}#}
{#                    <p>No clients available</p>#}
{#                {% endif %}#}
{#            </div>#}
{#        </div>#}
{##}
{#    {% else %}#}
{#        <h4>Access denied.</h4>#}
{#    {% endif %}#}
{#{% endblock %}#}

{#{% endblock %}#}

templates/index.html
{% extends 'base.html' %}
{% block main %}
<h4 class="card-title">Available People</h4>

{% if message %}
<p class="alert alert-success">
<strong>{{ message }}</strong>
</p>
{% endif %}
{% if latest_names %}
<ul>
{% for name in latest_names %}
 <li>
                <a href="/phonebook/{{ name.id }}/">
                    {{ name.person_name }}
                </a>
            </li>
{% endfor %}
</ul>
{% else %}
<p>No people are available right now.</p>
{% endif %}
{% endblock %}

templates/subscribe.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block main %}
<form action="" method="post">
{% csrf_token %}
{{ form|crispy }}
<button type="submit"
class="btn btn-success btn-block">
Subscribe</button>
<a href=".." class="btn btn-danger btn-block">
Back to home
</a>
</form>
{% endblock %}